/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.appanddata.alsme.model.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class KeyValue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5064896459097759954L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"KeyValue\",\"namespace\":\"com.appanddata.alsme.model.avro\",\"fields\":[{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"string\"},{\"name\":\"tombstone\",\"type\":\"boolean\",\"default\":false}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<KeyValue> ENCODER =
      new BinaryMessageEncoder<KeyValue>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<KeyValue> DECODER =
      new BinaryMessageDecoder<KeyValue>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<KeyValue> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<KeyValue> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<KeyValue> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<KeyValue>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this KeyValue to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a KeyValue from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a KeyValue instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static KeyValue fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence key;
   private java.lang.CharSequence value;
   private boolean tombstone;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public KeyValue() {}

  /**
   * All-args constructor.
   * @param key The new value for key
   * @param value The new value for value
   * @param tombstone The new value for tombstone
   */
  public KeyValue(java.lang.CharSequence key, java.lang.CharSequence value, java.lang.Boolean tombstone) {
    this.key = key;
    this.value = value;
    this.tombstone = tombstone;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return key;
    case 1: return value;
    case 2: return tombstone;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: key = (java.lang.CharSequence)value$; break;
    case 1: value = (java.lang.CharSequence)value$; break;
    case 2: tombstone = (java.lang.Boolean)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'key' field.
   * @return The value of the 'key' field.
   */
  public java.lang.CharSequence getKey() {
    return key;
  }


  /**
   * Sets the value of the 'key' field.
   * @param value the value to set.
   */
  public void setKey(java.lang.CharSequence value) {
    this.key = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public java.lang.CharSequence getValue() {
    return value;
  }


  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.CharSequence value) {
    this.value = value;
  }

  /**
   * Gets the value of the 'tombstone' field.
   * @return The value of the 'tombstone' field.
   */
  public boolean getTombstone() {
    return tombstone;
  }


  /**
   * Sets the value of the 'tombstone' field.
   * @param value the value to set.
   */
  public void setTombstone(boolean value) {
    this.tombstone = value;
  }

  /**
   * Creates a new KeyValue RecordBuilder.
   * @return A new KeyValue RecordBuilder
   */
  public static com.appanddata.alsme.model.avro.KeyValue.Builder newBuilder() {
    return new com.appanddata.alsme.model.avro.KeyValue.Builder();
  }

  /**
   * Creates a new KeyValue RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new KeyValue RecordBuilder
   */
  public static com.appanddata.alsme.model.avro.KeyValue.Builder newBuilder(com.appanddata.alsme.model.avro.KeyValue.Builder other) {
    if (other == null) {
      return new com.appanddata.alsme.model.avro.KeyValue.Builder();
    } else {
      return new com.appanddata.alsme.model.avro.KeyValue.Builder(other);
    }
  }

  /**
   * Creates a new KeyValue RecordBuilder by copying an existing KeyValue instance.
   * @param other The existing instance to copy.
   * @return A new KeyValue RecordBuilder
   */
  public static com.appanddata.alsme.model.avro.KeyValue.Builder newBuilder(com.appanddata.alsme.model.avro.KeyValue other) {
    if (other == null) {
      return new com.appanddata.alsme.model.avro.KeyValue.Builder();
    } else {
      return new com.appanddata.alsme.model.avro.KeyValue.Builder(other);
    }
  }

  /**
   * RecordBuilder for KeyValue instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<KeyValue>
    implements org.apache.avro.data.RecordBuilder<KeyValue> {

    private java.lang.CharSequence key;
    private java.lang.CharSequence value;
    private boolean tombstone;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.appanddata.alsme.model.avro.KeyValue.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.key)) {
        this.key = data().deepCopy(fields()[0].schema(), other.key);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.tombstone)) {
        this.tombstone = data().deepCopy(fields()[2].schema(), other.tombstone);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing KeyValue instance
     * @param other The existing instance to copy.
     */
    private Builder(com.appanddata.alsme.model.avro.KeyValue other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.key)) {
        this.key = data().deepCopy(fields()[0].schema(), other.key);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tombstone)) {
        this.tombstone = data().deepCopy(fields()[2].schema(), other.tombstone);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'key' field.
      * @return The value.
      */
    public java.lang.CharSequence getKey() {
      return key;
    }


    /**
      * Sets the value of the 'key' field.
      * @param value The value of 'key'.
      * @return This builder.
      */
    public com.appanddata.alsme.model.avro.KeyValue.Builder setKey(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.key = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'key' field has been set.
      * @return True if the 'key' field has been set, false otherwise.
      */
    public boolean hasKey() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'key' field.
      * @return This builder.
      */
    public com.appanddata.alsme.model.avro.KeyValue.Builder clearKey() {
      key = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public java.lang.CharSequence getValue() {
      return value;
    }


    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public com.appanddata.alsme.model.avro.KeyValue.Builder setValue(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.value = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public com.appanddata.alsme.model.avro.KeyValue.Builder clearValue() {
      value = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'tombstone' field.
      * @return The value.
      */
    public boolean getTombstone() {
      return tombstone;
    }


    /**
      * Sets the value of the 'tombstone' field.
      * @param value The value of 'tombstone'.
      * @return This builder.
      */
    public com.appanddata.alsme.model.avro.KeyValue.Builder setTombstone(boolean value) {
      validate(fields()[2], value);
      this.tombstone = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'tombstone' field has been set.
      * @return True if the 'tombstone' field has been set, false otherwise.
      */
    public boolean hasTombstone() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'tombstone' field.
      * @return This builder.
      */
    public com.appanddata.alsme.model.avro.KeyValue.Builder clearTombstone() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public KeyValue build() {
      try {
        KeyValue record = new KeyValue();
        record.key = fieldSetFlags()[0] ? this.key : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.value = fieldSetFlags()[1] ? this.value : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.tombstone = fieldSetFlags()[2] ? this.tombstone : (java.lang.Boolean) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<KeyValue>
    WRITER$ = (org.apache.avro.io.DatumWriter<KeyValue>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<KeyValue>
    READER$ = (org.apache.avro.io.DatumReader<KeyValue>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.key);

    out.writeString(this.value);

    out.writeBoolean(this.tombstone);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.key = in.readString(this.key instanceof Utf8 ? (Utf8)this.key : null);

      this.value = in.readString(this.value instanceof Utf8 ? (Utf8)this.value : null);

      this.tombstone = in.readBoolean();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.key = in.readString(this.key instanceof Utf8 ? (Utf8)this.key : null);
          break;

        case 1:
          this.value = in.readString(this.value instanceof Utf8 ? (Utf8)this.value : null);
          break;

        case 2:
          this.tombstone = in.readBoolean();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










